___

<a href="https://lms.clarusway.com/course/view.php?id=37"><img align="center" src="https://i.ibb.co/6Z5pQxD/lmss.png" alt="Open in Clarusway LMS" width="70" height="200" title="Open Clarusway Learning Management Sytem"></a>

<a href="https://github.com/clarusway/DS-DE-0322-Students/blob/main/3-%20Classes%26Labs/3-DVwPY/DVwPy_S06_Capstone_Project%20(Bike%20Store%20Sharing).ipynb"><img align="left" src="https://i.ibb.co/n3HWyQX/github-logo.png" alt="Open in Clarusway GitHub" width="100" height="150" title="Open and Execute in Clarusway GitHub Repository"></a>

<a href="https://nbviewer.org/github/4dsolutions/clarusway_data_analysis/blob/main/DVwPY_S6/6-DVwPy%20Capstone%20%28Bike%20Store%20Sharing%29.ipynb"><img align="right" src="https://i.ibb.co/48wtV8c/nbviewer-badge.png" alt="Open in nbviewer" width="130" height="200" title="Open and Execute in nbviewer"></a><br/>
___

<a href="https://clarusway.com/"><img align="center" src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" alt="CLRSWY" width="450" height="200" title="Welcome to Place Where You can Reinvent Yourself"></a><br/>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#9d4f8c; font-size:120%; text-align:center; border-radius:10px 10px;">Way to Reinvent Yourself</p>

<p style="text-align: center;"><img src="https://i.ibb.co/99DQ3TY/DS-Courses.png" class="img-fluid" 
alt="CLRSWY"></p>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#060108; font-size:200%; text-align:center; border-radius:10px 10px;">Data Analysis with Python</p>

![Image_Assignment](https://i.ibb.co/cY9HhF7/bnote-assignment.gif)

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#4d77cf; font-size:200%; text-align:center; border-radius:10px 10px;">Assignment 01 (NumPy & Pandas Basics)</p>

# Yeni Bölüm

<a id="toc"></a>

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Content</p>

* [NUMPY SECTION](#0)
* [PANDAS SECTION](#1)


**In this assignment you will start off with Numpy Exercises and then complete the whole Exercise with Pandas questions. All the subjects related to questions here already covered in preclass materials and in-class sessions. So good luck!**

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Numpy Section</p>

<a id="0"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

### 1. Import NumPy Library.

In [72]:
# YOUR CODE IS HERE
import numpy  as np


### 2. Create an array from my_list = [5, 10, 15, 20, 25]

In [73]:
# YOUR CODE IS HERE

my_list = [5, 10, 15, 20, 25]
my_first_array = np.array(my_list)
my_first_array

array([ 5, 10, 15, 20, 25])

### 3. Generate an array of 5x5 with zeros. 

In [74]:
# YOUR CODE IS HERE

np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

### 4. Generate an array of 4x4 with ones and assign data type as int.

In [75]:
# YOUR CODE IS HERE

(np.ones((4,4))).astype(int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

### 5. Make all the values of the array above with the value of 7.

In [76]:
# YOUR CODE IS HERE

arr = np.ones((4,4))
for i in range(len(arr)) :                                    
      arr[i ] = 7
arr.astype(int)


array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

### 6. Create the previous array above by full() method.

In [77]:
# YOUR CODE IS HERE

arr_1 = np.full((4 , 4) , 7)
arr_1

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

### 7. Create an array of even integers from 2 to 16 (inclusive). 

In [78]:
# YOUR CODE IS HERE
arr_2 = np.arange(2 , 17 , 2)
arr_2

array([ 2,  4,  6,  8, 10, 12, 14, 16])

### 8. Create a 5x5 matrix with the values between 0 to 25 (exclusive).

In [79]:
# YOUR CODE IS HERE
arr = np.arange(0,25).reshape(5,5)
arr




array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### 9. Create a 5x5 matrix with the values between 0 to 25 (exclusive) using linspace method.

In [80]:
# YOUR CODE IS HERE
array = np.linspace(0, 24 , 25).reshape(5 ,5)
array.astype(int)


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### 10. Create randomly 5 numbers with numpy.

In [81]:
# YOUR CODE IS HERE

array = np.random.rand(5)
array


array([0.1666009 , 0.29797952, 0.98548633, 0.12580077, 0.04745496])

### 11. Create an array of 5*5 shape and fills it with random values as per the standard normal distribution.

In [82]:
# YOUR CODE IS HERE
np.random.randn(5 ,5)


array([[ 0.46485116, -0.44539257,  0.23977187,  0.40185405, -0.86062483],
       [ 0.80978881,  0.5387072 ,  0.43881352,  0.1154996 ,  1.22418794],
       [-0.48581287, -0.30470684,  0.20831376, -1.45905526,  0.68435846],
       [-0.47536218,  0.51655531,  0.85194531, -0.08554265,  0.54335567],
       [-0.28271076, -0.35297235,  0.83826099, -1.33472975,  0.17588354]])

### 12. Create a 3*4 array of random int numbers between 20 and 50.

In [ ]:
# YOUR CODE IS HERE

np.random.randint(20, 50 , size = (3 ,4))

array([[40, 28, 41, 21],
       [28, 24, 23, 33],
       [41, 35, 21, 44]])

### 13. Create an array named "ranarr"consisting of randomly 48 numbers and reshape this array with the shape of 6x8 in different ways.

In [22]:
# YOUR CODE IS HERE

ranarr = np.random.randint(20,100 , 48)
ranarr

array([91, 54, 97, 47, 60, 35, 22, 86, 99, 61, 81, 41, 29, 73, 43, 23, 43,
       22, 50, 85, 37, 33, 25, 57, 23, 44, 54, 38, 62, 27, 93, 24, 79, 27,
       55, 28, 51, 23, 99, 54, 23, 96, 74, 86, 40, 67, 69, 51])

In [23]:
# YOUR CODE IS HERE (RESHAPING WITH NUM)
ranarr.reshape(6 ,8)


array([[91, 54, 97, 47, 60, 35, 22, 86],
       [99, 61, 81, 41, 29, 73, 43, 23],
       [43, 22, 50, 85, 37, 33, 25, 57],
       [23, 44, 54, 38, 62, 27, 93, 24],
       [79, 27, 55, 28, 51, 23, 99, 54],
       [23, 96, 74, 86, 40, 67, 69, 51]])

In [25]:
# YOUR CODE IS HERE (RESHAPING WITH -1)

ranarr.reshape(-1 , 8)     #tekrar bak
ranarr

array([91, 54, 97, 47, 60, 35, 22, 86, 99, 61, 81, 41, 29, 73, 43, 23, 43,
       22, 50, 85, 37, 33, 25, 57, 23, 44, 54, 38, 62, 27, 93, 24, 79, 27,
       55, 28, 51, 23, 99, 54, 23, 96, 74, 86, 40, 67, 69, 51])

In [20]:
# YOUR CODE IS HERE (RESHAPING WITH -1)

ranarr.reshape(6 , -1)

array([[0.78372315, 0.93703883, 0.99380094, 0.35929395, 0.23375414,
        0.56965194, 0.94107929, 0.58324921],
       [0.2481845 , 0.35291699, 0.95965967, 0.2703363 , 0.7922001 ,
        0.30343018, 0.6332876 , 0.64022457],
       [0.87801006, 0.86825652, 0.37638565, 0.57314366, 0.35461005,
        0.06188072, 0.82549392, 0.01085638],
       [0.19379889, 0.65325547, 0.22076666, 0.18670637, 0.94368934,
        0.2400869 , 0.13290676, 0.25827062],
       [0.1568771 , 0.62114087, 0.63916958, 0.05662051, 0.60209206,
        0.8968483 , 0.08535265, 0.87993742],
       [0.2949251 , 0.07024279, 0.15550906, 0.00424347, 0.74640026,
        0.8428621 , 0.8742713 , 0.80301169]])

## Numpy Indexing and Selection

### Create an array named "mat" in accordence with the desired output below.

In [36]:
# YOUR CODE IS HERE 
mat = np.array([[1 ,2 ,3 , 4] , [5 , 6 , 7 , 8] , [9 ,10 ,11 , 12] , [13 , 14 , 15 , 16]])
mat


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

### 14. Using the array above, write a code that reproduces the desired output shown below.<br>

In [37]:
# YOUR CODE IS HERE 
mat[1:3 ,1:3]


array([[ 6,  7],
       [10, 11]])

### 15. Get the 1st column (index number 0) of the array above.

In [38]:
# YOUR CODE IS HERE      # PARANTEZLER OLMADI KONTROL!!!!!!!
mat[ : , 0]

array([ 1,  5,  9, 13])

### 16. Get the values in 2nd row (index number 1) for every 2 step.

In [39]:
# YOUR CODE IS HERE 
mat[1 , :: 2]

array([5, 7])

### 17.Assign 77 to every cell in 3rd column.

In [42]:
# YOUR CODE IS HERE 
mat[: , 2]= 77
mat

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

### 18. (a) Take 2nd row (index number 1) and 1st column (index number 0) , (b) 4th row (index number 3) and 3rd column (index number 2) .

In [43]:
# YOUR CODE IS HERE 
np.array([mat[1,0],mat[3 , 2]])                




array([ 5, 77])

### 19. Take between 2nd and last row with step 2 and between 1st and last column with step 2.

In [ ]:
# YOUR CODE IS HERE 
mat[1: :2 , :3:2]

array([[ 5, 77],
       [13, 77]])

## NumPy Operations

### 20. Get the sum of values smaller than 10 and values bigger than 12 in "mat".

In [ ]:
# LET US REMEMBER OUR ARRAY OF "mat" 

# YOUR CODE IS HERE 

mat

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

In [ ]:
# LET US FIND THE VALUES SMALLER THAN 10 IN "mat" 

# YOUR CODE IS HERE 

mat[mat<10]

array([1, 2, 4, 5, 6, 8, 9])

In [ ]:
# LET US FIND THE VALUES BIGGER THAN 12 IN "mat" 

# YOUR CODE IS HERE
mat[mat>12]

array([77, 77, 77, 13, 14, 77, 16])

In [ ]:
# LET US SUM THE VALUES SMALLER THAN 10 AND BIGGER THAN 12 IN "mat" 

# YOUR CODE IS HERE 

arr_1= mat[(mat<10)] + mat[(mat>12)]
arr_1



array([78, 79, 81, 18, 20, 85, 25])

### 21. Get the standard deviation (std) of the result above.

In [ ]:
# YOUR CODE IS HERE 

arr_1

array([78, 79, 81, 18, 20, 85, 25])

### 22. Get the sum of the 2nd column in the original "mat".

In [ ]:
# LET US REMEMBER OUR ARRAY OF "mat" 

# YOUR CODE IS HERE 
mat


array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

In [ ]:
# LET US OBTAIN THE ORIGINAL ARRAY OF "mat"                                                      

# YOUR CODE IS HERE 
mat = np.array([[1 ,2 ,3 , 4] , [5 , 6 , 7 , 8] , [9 ,10 ,11 , 12] , [13 , 14 , 15 , 16]])
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
# YOUR CODE IS HERE 
toplam =np.sum(mat[: , 1])
toplam


32

### 23. Get the median, mean and std of 3rd column in "mat".

In [51]:
# LET US REMEMBER OUR ARRAY OF "mat" 

# YOUR CODE IS HERE 
mat


array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

In [50]:
# LET US ASSIGN THE COLUMN WE ARE INTERESTED IN TO A VARIABLE 

# YOUR CODE IS HERE 

sutun =mat[: , 2].reshape(4 , -1)                                          #karıştırdığım yer dikkat önce tek kapalıda yapmıştım istenen hepsi ayrı ayrı!!!!
sutun

array([77, 77, 77, 77])

In [52]:
# WHAT IF WE ARE INTERESTED IN THE 3RD ROW? 

# YOUR CODE IS HERE 

satır = mat[2, :]
satır

array([ 9, 10, 77, 12])

In [ ]:
# LET US GET MEDIAN VALUE 

# YOUR CODE IS HERE 

sutun_median = np.median(sutun)
sutun_median      
satır_median = np.median(satır)
satır_median      


9.0

In [ ]:
# LET US GET MEAN VALUE 

# YOUR CODE IS HERE                                      #nerenin meanını soruyor?????

sutun_mean = np.mean(sutun)
sutun_mean 

9.0

In [ ]:
# LET US GET STANDART DEVIATION (std) VALUE 

# YOUR CODE IS HERE                                        #nerenin std soruyor?????
std_1= np.std(sutun)
std_1

4.47213595499958

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Pandas Section</p>

<a id="1"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

### Import Pandas Library

In [54]:
# YOUR CODE IS HERE 

import pandas as pd


# Yeni Bölüm

# Yeni Bölüm

### Read Salaries.csv and take a look at the first 5 rows, df info and df statistical measurements.*

In [55]:
# LET US READ Salaries.csv 

# YOUR CODE IS HERE 
dataframe = pd.read_csv("Salaries.csv")

In [5]:
# LET US LOOK AT THE FIRST 5 ROWS 

# YOUR CODE IS HERE 
dataframe.head(5)


Id       EmployeeName                                        JobTitle  \
0   1     NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1   2       GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2   3     ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3   4  CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4   5    PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   

     BasePay  OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  \
0  167411.18         0.00  400184.25       NaN  567595.43         567595.43   
1  155966.02    245131.88  137811.38       NaN  538909.28         538909.28   
2  212739.13    106088.18   16452.60       NaN  335279.91         335279.91   
3   77916.00     56120.71  198306.90       NaN  332343.61         332343.61   
4  134401.60      9737.00  182234.59       NaN  326373.19         326373.19   

   Year  Notes         Agency  Status  
0  2011    NaN  San Francisco     NaN  
1  2011    NaN  San Francisco     NaN  
2  2011    NaN  San Francisco     NaN  
3  2011    NaN  San Francisco     NaN  
4  2011    NaN  San Francisco     NaN

Desired Output:

![image.png](https://i.ibb.co/6BTmGX8/assignment1a.png)

In [6]:
# LET US GET A SAMPLE 

# YOUR CODE IS HERE 

dataframe.sample(1)

Id    EmployeeName                              JobTitle  BasePay  \
33985  33986  EVANS ANDERSON  PUBLIC SERVICE AIDE-SPECIAL PROGRAMS  3505.65   

       OvertimePay  OtherPay  Benefits  TotalPay  TotalPayBenefits  Year  \
33985          0.0     76.59       NaN   3582.24           3582.24  2011   

       Notes         Agency  Status  
33985    NaN  San Francisco     NaN

Desired Output (WATCH OUT! Your output may NOT be the same as the one):

![image.png](https://i.ibb.co/mcsCxxC/assignment1b.png)

In [7]:
# YOUR CODE IS HERE 
dataframe.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype  
---  ------            --------------   -----  
 0   Id                148654 non-null  int64  
 1   EmployeeName      148654 non-null  object 
 2   JobTitle          148654 non-null  object 
 3   BasePay           148045 non-null  float64
 4   OvertimePay       148650 non-null  float64
 5   OtherPay          148650 non-null  float64
 6   Benefits          112491 non-null  float64
 7   TotalPay          148654 non-null  float64
 8   TotalPayBenefits  148654 non-null  float64
 9   Year              148654 non-null  int64  
 10  Notes             0 non-null       float64
 11  Agency            148654 non-null  object 
 12  Status            0 non-null       float64
dtypes: float64(8), int64(2), object(3)
memory usage: 14.7+ MB


In [8]:
# LET US GET SOME DESCRIPTIVE MEASUREMENTS  

# YOUR CODE IS HERE 
dataframe.describe()


Id        BasePay    OvertimePay       OtherPay  \
count  148654.000000  148045.000000  148650.000000  148650.000000   
mean    74327.500000   66325.448840    5066.059886    3648.767297   
std     42912.857795   42764.635495   11454.380559    8056.601866   
min         1.000000    -166.010000      -0.010000   -7058.590000   
25%     37164.250000   33588.200000       0.000000       0.000000   
50%     74327.500000   65007.450000       0.000000     811.270000   
75%    111490.750000   94691.050000    4658.175000    4236.065000   
max    148654.000000  319275.010000  245131.880000  400184.250000   

            Benefits       TotalPay  TotalPayBenefits           Year  Notes  \
count  112491.000000  148654.000000     148654.000000  148654.000000    0.0   
mean    25007.893151   74768.321972      93692.554811    2012.522643    NaN   
std     15402.215858   50517.005274      62793.533483       1.117538    NaN   
min       -33.890000    -618.130000       -618.130000    2011.000000    NaN   
25%     11535.395000   36168.995000      44065.650000    2012.000000    NaN   
50%     28628.620000   71426.610000      92404.090000    2013.000000    NaN   
75%     35566.855000  105839.135000     132876.450000    2014.000000    NaN   
max     96570.660000  567595.430000     567595.430000    2014.000000    NaN   

       Status  
count     0.0  
mean      NaN  
std       NaN  
min       NaN  
25%       NaN  
50%       NaN  
75%       NaN  
max       NaN

Desired Output:

![image.png](https://i.ibb.co/ftMP67H/assignmnet1c.png)

### How many different year values are there?

In [65]:
# YOUR CODE IS HERE 
unique= dataframe.Year.value_counts()
       
                                                    

In [66]:
# LET US FIND THE NUMBER OF UNIQUE VALUES IN THE COLUMN OF "Year"

# YOUR CODE IS HERE 
unique.count()


4

In [15]:
# LET US FIND THE UNIQUE VALUES IN THE COLUMN OF "Year"

# YOUR CODE IS HERE 

dataframe["Year"].unique()

array([2011, 2012, 2013, 2014], dtype=int64)

### Print out max and avg values in the column of "Totalpay".

In [16]:
# LET US FIND THE MAXIMUM TOTALPAY

# YOUR CODE IS HERE 
dataframe["TotalPay"].max()


567595.43

In [17]:
# LET US FIND THE AVERAGE TOTALPAY

# YOUR CODE IS HERE 

dataframe["TotalPay"].mean()

74768.32197169267

### How many records in the TotalPay column are there bigger than avg TotalPay?

In [18]:
# YOUR CODE IS HERE 
mean_year =dataframe["TotalPay"].mean()
df_year =dataframe[dataframe['TotalPay'] > mean_year]
df_year



Id       EmployeeName  \
0            1     NATHANIEL FORD   
1            2       GARY JIMENEZ   
2            3     ALBERT PARDINI   
3            4  CHRISTOPHER CHONG   
4            5    PATRICK GARDNER   
...        ...                ...   
135701  135702    Christina S Jee   
135778  135779  Mary Ann T Abille   
135847  135848   Emilda E Reinosa   
135853  135854      David G Evans   
136063  136064         Nicole Joe   

                                              JobTitle    BasePay  \
0       GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  167411.18   
1                      CAPTAIN III (POLICE DEPARTMENT)  155966.02   
2                      CAPTAIN III (POLICE DEPARTMENT)  212739.13   
3                 WIRE ROPE CABLE MAINTENANCE MECHANIC   77916.00   
4         DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)  134401.60   
...                                                ...        ...   
135701                              Nurse Practitioner   70635.61   
135778                                   Special Nurse   60889.34   
135847                                   Special Nurse   76305.74   
135853                                   Special Nurse   71178.15   
136063                                   Special Nurse   61276.59   

        OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  Year  \
0              0.00  400184.25       NaN  567595.43         567595.43  2011   
1         245131.88  137811.38       NaN  538909.28         538909.28  2011   
2         106088.18   16452.60       NaN  335279.91         335279.91  2011   
3          56120.71  198306.90       NaN  332343.61         332343.61  2011   
4           9737.00  182234.59       NaN  326373.19         326373.19  2011   
...             ...        ...       ...        ...               ...   ...   
135701         0.00    6550.41    771.88   77186.02          77957.90  2014   
135778      6815.67    9041.21    767.47   76746.22          77513.69  2014   
135847         0.00       0.00    763.08   76305.74          77068.82  2014   
135853      2748.15    2354.40    762.81   76280.70          77043.51  2014   
136063      8538.44    5078.67    748.95   74893.70          75642.65  2014   

        Notes         Agency  Status  
0         NaN  San Francisco     NaN  
1         NaN  San Francisco     NaN  
2         NaN  San Francisco     NaN  
3         NaN  San Francisco     NaN  
4         NaN  San Francisco     NaN  
...       ...            ...     ...  
135701    NaN  San Francisco     NaN  
135778    NaN  San Francisco     NaN  
135847    NaN  San Francisco     NaN  
135853    NaN  San Francisco     NaN  
136063    NaN  San Francisco     NaN  

[69489 rows x 13 columns]

Desired Output:

![image.png](https://i.ibb.co/nj84FbZ/assignment1d.png)

In [19]:
# YOUR CODE IS HERE 

dataframe[dataframe['TotalPay'] > mean_year].shape[0]        #shape[0] satır sayılarını verir

69489

### How much does ALBERT PARDINI make money (including benefits)?

In [68]:
# YOUR CODE IS HERE 
dataframe.loc[[2], "TotalPayBenefits"]            

2    335279.91
Name: TotalPayBenefits, dtype: float64

### Who is the lowest paid person?

In [69]:
# YOUR CODE IS HERE 
lowest_paid_person =dataframe.sort_values(by="TotalPayBenefits" , ascending = True)                          #ascending=True artan değerlere göre sıralama
lowest_paid_person.loc[[148653] , "EmployeeName"]                                             

148653    Joe Lopez
Name: EmployeeName, dtype: object

### What are the unique Jobs in dataset?

In [24]:
# YOUR CODE IS HERE 

dataframe["JobTitle"].unique()


array(['GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY',
       'CAPTAIN III (POLICE DEPARTMENT)',
       'WIRE ROPE CABLE MAINTENANCE MECHANIC', ..., 'Conversion',
       'Cashier 3', 'Not provided'], dtype=object)

### List the top 3 least common Jobs in the dataset.

In [25]:
# YOUR CODE IS HERE 

dataframe["JobTitle"].value_counts().tail(3)

COURT COMPUTER FACILITIES COORDINATOR             1
AUTOMOTIVE BODY AND FENDER WORKER SUPERVISOR I    1
VICTIM & WITNESS TECHNICIAN                       1
Name: JobTitle, dtype: int64

### How many people earned more than avg in 2012?

In [71]:
# YOUR CODE IS HERE 
dataframe[(dataframe.Year==2012) & (dataframe["TotalPayBenefits"] > dataframe["TotalPayBenefits"].mean())].shape[0]                  #sonuç farklı çıktı!!!!!

20366

### How many people have a title of Manager in their jobs?

In [56]:
# USE APPLY FUNCTION FOR THIS QUESTION!

# YOUR CODE IS HERE 
Manager = dataframe.filter(regex ="Manager" , axis=1)
mjobs= dataframe["JobTitle"].apply(lambda x : x == Manager)
mjobs.sum()
                                                                 #yapamadım :( hem apply hem regex kullanılabilir mi??

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, ...]

[148654 rows x 0 columns]

In [ ]:
def jobtitle (job_title) :
    if "manager" in jobtitle.lower

### Take Id, EmployeeName, JobTitle, TotalPay and TotalPayBenefits columns with iloc and assign them as sal_new dataframe.

In [35]:
# YOUR CODE IS HERE 

sal_new = dataframe.iloc[ : , [0 , 1 , 2 , 7 , 8] ] 

Desired Output:

![image.png](https://i.ibb.co/ZgFCbPm/assignment1e.png)

### Take the columns betweeen EmployeeName and TotalPayBenefits with loc and assign them as sal_new df.

In [40]:
# YOUR CODE IS HERE 

sal_new = dataframe.loc[ : , "EmployeeName" : "TotalPayBenefits"]
sal_new

EmployeeName                                        JobTitle  \
0          NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1            GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2          ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3       CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4         PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   
...                   ...                                             ...   
148649      Roy I Tillery                                       Custodian   
148650       Not provided                                    Not provided   
148651       Not provided                                    Not provided   
148652       Not provided                                    Not provided   
148653          Joe Lopez                      Counselor, Log Cabin Ranch   

          BasePay  OvertimePay   OtherPay  Benefits   TotalPay  \
0       167411.18         0.00  400184.25       NaN  567595.43   
1       155966.02    245131.88  137811.38       NaN  538909.28   
2       212739.13    106088.18   16452.60       NaN  335279.91   
3        77916.00     56120.71  198306.90       NaN  332343.61   
4       134401.60      9737.00  182234.59       NaN  326373.19   
...           ...          ...        ...       ...        ...   
148649       0.00         0.00       0.00       0.0       0.00   
148650        NaN          NaN        NaN       NaN       0.00   
148651        NaN          NaN        NaN       NaN       0.00   
148652        NaN          NaN        NaN       NaN       0.00   
148653       0.00         0.00    -618.13       0.0    -618.13   

        TotalPayBenefits  
0              567595.43  
1              538909.28  
2              335279.91  
3              332343.61  
4              326373.19  
...                  ...  
148649              0.00  
148650              0.00  
148651              0.00  
148652              0.00  
148653           -618.13  

[148654 rows x 8 columns]

Desired Output:

![image.png](https://i.ibb.co/s2CYS7H/assignment1f.png)

### Print out the names of the employees who earn more than min but less than avg.

In [48]:
# YOUR CODE IS HERE 
avg = dataframe["TotalPayBenefits"].mean()
dataframe[["EmployeeName" , "TotalPayBenefits"]][(dataframe["TotalPayBenefits"] < avg) & (dataframe["TotalPayBenefits"] > dataframe["TotalPayBenefits"].min())]

EmployeeName  TotalPayBenefits
10806          KWE LEE          93691.15
10807   MIGUEL CARO JR          93682.74
10808    JOANNE MORRIS          93680.53
10809    LAYLA WELBORN          93676.88
10810          LE BANH          93675.39
...                ...               ...
148648     Leon Walker              0.00
148649   Roy I Tillery              0.00
148650    Not provided              0.00
148651    Not provided              0.00
148652    Not provided              0.00

[75649 rows x 2 columns]

Desired Output:

![image.png](https://i.ibb.co/mtNB2TX/assignment1g.png)

<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" 
alt="CLRSWY"></p>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#9d4f8c; font-size:100%; text-align:center; border-radius:10px 10px;">WAY TO REINVENT YOURSELF</p>

________